(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
			 ("nongnu" . "https://elpa.nongnu.org/nongnu/")
                         ("melpa" . "https://melpa.org/packages/")))

(package-refresh-contents)

(unless (package-installed-p 'evil)
  (package-install 'evil))
(unless (package-installed-p 'doom-modeline)
  (package-install 'doom-modeline))
(unless (package-installed-p 'vertico)
  (package-install 'vertico))
(unless (package-installed-p 'doom-themes)
  (package-install 'doom-themes))
(unless (package-installed-p 'orderless)
  (package-install 'orderless))
(unless (package-installed-p 'consult)
  (package-install 'consult))
(unless (package-installed-p 'dashboard)
  (package-install 'dashboard))
(unless (package-installed-p 'dirvish)
  (package-install 'dirvish))
(unless (package-installed-p 'which-key)
  (package-install 'which-key))
(unless (package-installed-p 'typst-ts-mode)
  (package-install 'typst-ts-mode))
(unless (package-installed-p 'diredfl)
  (package-install 'diredfl))
(unless (package-installed-p 'evil-commentary)
  (package-install 'evil-commentary))
(unless (package-installed-p 'highlight-defined)
  (package-install 'highlight-defined))
(unless (package-installed-p 'highlight-quoted)
  (package-install 'highlight-quoted))
(unless (package-installed-p 'rainbow-delimiters)
  (package-install 'rainbow-delimiters))
(unless (package-installed-p 'eglot)
  (package-install 'eglot))
(unless (package-installed-p 'markdown-mode)
  (package-install 'markdown-mode))
(unless (package-installed-p 'xclip)
  (package-install 'xclip))
(unless (package-installed-p 'elcord)
  (package-install 'elcord))
(unless (package-installed-p 'magit)
  (package-install 'magit))
(unless (package-installed-p 'dtrt-indent)
  (package-install 'dtrt-indent))
(unless (package-installed-p 'evil-org)
  (package-install 'evil-org))
(unless (package-installed-p 'org-modern)
  (package-install 'org-modern))
(unless (package-installed-p 'code-cells)
  (package-install 'code-cells))

(require 'evil)
(require 'doom-modeline)
(require 'vertico)
(require 'doom-themes)
(require 'orderless)
(require 'consult)
(require 'dashboard)
(require 'dirvish)
(require 'which-key)
(require 'typst-ts-mode)
(require 'diredfl)
(require 'evil-commentary)
(require 'highlight-defined)
(require 'highlight-quoted)
(require 'rainbow-delimiters)
(require 'eglot)
(require 'xclip)
(require 'elcord)
(require 'magit)
(require 'dtrt-indent)
(require 'evil-org)
(require 'evil-org-agenda)
(require 'org-modern)
(require 'code-cells)
